package fr.cnrs.liris.tagomatic.entities;


//This class contains store tag ranks generated by different ranking schemes
public class TagRank {

	
	private double freqRelWordsAndAllUsers;
	private double freqRelWordAndOnlyUniqueUser;
	private double freqRelOnlyWord;
	
	private double tfIdfRelWordsAndAllUsers;
	private double tfIdfRelWordAndOnlyUniqueUser;
	private double tfIdfRelOnlyWord;
	
	
	public double getFreqRelWordsAndAllUsers() {
		return freqRelWordsAndAllUsers;
	}
	public void setFreqRelWordsAndAllUsers(double freqRelWordsAndAllUsers) {
		this.freqRelWordsAndAllUsers = freqRelWordsAndAllUsers;
	}
	public double getFreqRelWordAndOnlyUniqueUser() {
		return freqRelWordAndOnlyUniqueUser;
	}
	public void setFreqRelWordAndOnlyUniqueUser(double freqRelWordAndOnlyUniqueUser) {
		this.freqRelWordAndOnlyUniqueUser = freqRelWordAndOnlyUniqueUser;
	}
	public double getFreqRelOnlyWord() {
		return freqRelOnlyWord;
	}
	public void setFreqRelOnlyWord(double freqRelOnlyWord) {
		this.freqRelOnlyWord = freqRelOnlyWord;
	}
	public double getTfIdfRelWordsAndAllUsers() {
		return tfIdfRelWordsAndAllUsers;
	}
	public void setTfIdfRelWordsAndAllUsers(double tfIdfRelWordsAndAllUsers) {
		this.tfIdfRelWordsAndAllUsers = tfIdfRelWordsAndAllUsers;
	}
	public double getTfIdfRelWordAndOnlyUniqueUser() {
		return tfIdfRelWordAndOnlyUniqueUser;
	}
	public void setTfIdfRelWordAndOnlyUniqueUser(
			double tfIdfRelWordAndOnlyUniqueUser) {
		this.tfIdfRelWordAndOnlyUniqueUser = tfIdfRelWordAndOnlyUniqueUser;
	}
	public double getTfIdfRelOnlyWord() {
		return tfIdfRelOnlyWord;
	}
	public void setTfIdfRelOnlyWord(double tfIdfRelOnlyWord) {
		this.tfIdfRelOnlyWord = tfIdfRelOnlyWord;
	}
	
	
	@Override
	public String toString() {
		StringBuffer str = new StringBuffer(400);
		str.append("FR-NoUsers:").append(this.freqRelOnlyWord).append(",")
		.append("FR-AllUsers:").append(this.freqRelWordsAndAllUsers).append(",")
		.append("FR-UnqUsers:").append(this.freqRelWordAndOnlyUniqueUser).append(",")
		.append("TFIDF-NoUsers:").append(this.tfIdfRelOnlyWord).append(",")
		.append("TFIDF-AllUsers:").append(this.tfIdfRelWordsAndAllUsers).append(",")
		.append("TFIDF-UnqUsers:").append(this.tfIdfRelWordAndOnlyUniqueUser);
		
		return str.toString();
	}
	
	
	
}
